# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

PUT http://127.0.0.1:8080/customers/add
Content-Type: application/json

{
  "firstName": "Alice",
  "lastName": "Merton",
  "birthday": "1993-09-13"
}

###

PUT http://127.0.0.1:8080/gadgets/add
Content-Type: application/json

{
  "name": "light",
  "on": "true"
}

###

POST http://127.0.0.1:8080/gadgets/2/user?customerId=1

###

GET http://127.0.0.1:8080/gadgets/2

###

GET http://localhost:8080/customers/1

###

PUT http://127.0.0.1:8080/gadgets/add
Content-Type: application/json

{
  "name": "Christmaslight",
  "on": "true",
  "color" : {
    "red" : "0",
    "green" : "255",
    "blue" : "0"
  }
}

###